export const LIGHTMODE = "LIGHTMODE";
export const DARKMODE = "DARKMODE"
export const USER_START = "USER_START"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FAILIURE = "USER_FAILIURE"
export const  UPDATE_FAILURE = " UPDATE_FAILURE"
export const  UPDATE_SUCCESS = " UPDATE_SUCCESS"
export const  USER_LOGOUT = " USER_LOGOUT"
export const  UPDATE_START = " UPDATE_START"
export const BLOGS_BEGIN = "BLOGS_BEGIN"
export const BLOGS_SUCCESS = "BLOGS_SUCCESS"
export const BLOGS_ERROR = "BLOGS_ERROR"

export const SINGLE_POST = "SINGLE_POST" 
export const  SUPDATE_FAILURE = "SUPDATE_FAILURE"
export const  SUPDATE_SUCCESS = "SUPDATE_SUCCESS"

export const LOAD_BLOGS = "LOAD_BLOGS"
export const SET_GRIDVIEW = "SET_GRIDVIEW"
export const SET_LISTVIEW = "SET_LISTVIEW"
export const UPDATE_SORT = "UPDATE_SORT"
export const UPDATE_FILTER = "UPDATE_FILTER"
export const SORT_BLOGS = "SORT_BLOGS"
export const FILTER_BLOGS = "FILTER_BLOGS"
export const CLEAR_FILTER = "CLEAR_FILTER"